import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, PhoneCall } from "lucide-react";

interface LocalityHeroSectionProps { localityName: string; projectCount: string; heroImage: string; }

export default function LocalityHeroSection({ localityName, heroImage }: LocalityHeroSectionProps) {
  return <section data-quote-form="disabled" className="locality-hero relative isolate overflow-hidden bg-primary text-primary-foreground md:min-h-[620px]"><Image src={heroImage} alt={`Interior design in ${localityName}, Bangalore`} fill priority sizes="100vw" className="z-0 object-cover object-center" /><div className="absolute inset-0 z-10" style={{ background: "linear-gradient(90deg, rgba(7,31,43,.88) 0%, rgba(7,31,43,.76) 55%, rgba(7,31,43,.54) 100%)" }} /><div className="absolute inset-0 z-10" style={{ backgroundColor: "rgba(7,31,43,.38)" }} /><div className="container relative z-20 flex px-5 pb-12 pt-28 md:min-h-[620px] md:items-center md:px-8 md:py-24"><div className="max-w-2xl"><h1 className="hero-display text-[2.8rem] leading-[.98] text-primary-foreground sm:text-5xl md:text-[3.6rem]"><span className="block">Best Interior Designer</span><span className="block">in {localityName}, Bangalore</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-primary-foreground/90 md:text-lg">Thoughtful home interiors, transparent pricing, and an end-to-end process shaped around the way you live.</p><div className="hero-cta-row mt-8"><Link href="/contact" data-open-consultation className="hero-cta-primary inline-flex items-center gap-3 whitespace-nowrap bg-secondary py-4 text-sm font-semibold text-secondary-foreground shadow-[0_10px_22px_-12px_rgb(209_101_66_/_72%)]">Book a Free Consultation <ArrowUpRight className="h-4 w-4" /></Link><a href="tel:+919886579923" className="hero-cta-secondary inline-flex items-center gap-2 whitespace-nowrap border border-white/20 bg-black/35 py-4 text-sm font-semibold text-white backdrop-blur-sm"><PhoneCall className="h-4 w-4" /> Call Now</a></div></div></div></section>;
}
