export const BANGALORE_LOCALITY_SLUGS = [
  "indiranagar",
  "whitefield",
  "hsr-layout",
  "koramangala",
  "jp-nagar",
  "jayanagar",
  "marathahalli",
  "electronic-city",
  "sarjapur-road",
  "bellandur",
  "btm-layout",
  "hebbal",
  "yelahanka",
  "banashankari",
  "malleshwaram",
  "rajajinagar",
  "basavanagudi",
  "sadashivanagar",
  "rt-nagar",
  "vijayanagar",
  "hbr-layout",
] as const;
