import Image from "next/image";
import Link from "next/link";
import heroImage from "@/assets/hero-interior.jpg";
import { companies, checklist, faqs } from "@/content/interior-comparison";
import { Section, ConsultationLink, ClaimSource } from "./ComparisonSections";
import PrintChecklist from "./PrintChecklist";

export function EverySpacesDifference() {
  const company = companies[4];
  return <Section id="everyspaces" title="Where EverySpaces Fits In" eyebrow="Our approach">
    <div className="grid items-start gap-10 lg:grid-cols-2"><div className="journal-prose"><p className="!text-xl">EverySpaces is for homeowners who want an organised design process and a home considered around the way they live.</p><p>{company.overview.text} {company.understand} <ClaimSource claim={company.overview} /></p><p>Start by telling us what is not working today. Perhaps kitchen storage is difficult to reach, a bedroom needs a work corner, or the living room has to accommodate both family evenings and guests. Those practical details give a design conversation direction.</p><p>Explore our <Link href="/services/full-home-design">full-home interiors</Link>, <Link href="/services/2bhk-interiors">2BHK</Link> and <Link href="/services/3bhk-interiors">3BHK services</Link>. We also work on <Link href="/services/modular-kitchen">modular kitchens</Link>, <Link href="/services/wardrobe-design">wardrobes</Link>, <Link href="/services/living-room">living spaces</Link>, <Link href="/services/bedroom-design">bedrooms</Link>, <Link href="/services/kids-room">kids’ rooms</Link> and <Link href="/services/home-office">home offices</Link>.</p><p>Judge our work with the same care you apply to another company. Ask for a proposal you can follow, a realistic sequence of decisions and a clear explanation of what happens when something changes.</p><div className="flex flex-wrap gap-4"><Link href="/portfolio" className="journal-button">See Our Projects</Link><ConsultationLink>Start Your Project</ConsultationLink></div></div><div><Image src={heroImage} alt="A warm living space with layered seating and natural finishes" sizes="(min-width: 1024px) 45vw, 100vw" className="aspect-[4/5] w-full rounded-3xl object-cover" /><p className="mt-4 text-sm text-muted-foreground">A home begins with your routines, priorities and ideas.</p></div></div>
  </Section>;
}

export function PricingExplainer() {
  return <Section id="pricing" title="What Does Home Interior Design Cost in Bangalore?" eyebrow="First compare the scope">
    <div className="journal-prose"><p>There is no useful single price for every home. Two apartments with the same bedroom count can need very different amounts of work. Home size matters, but so do the number of rooms you furnish, kitchen dimensions, wardrobe quantities and the condition of the site.</p><p>A quotation also reflects the board, shutter finish, laminate, hardware and drawer systems you select. False ceilings, electrical changes, painting, civil work, loose furniture and custom details can sit outside a modular package. Ask where each of these appears in your estimate.</p><p>Start with a list of essentials and a separate list of upgrades. This makes it easier to decide what to prioritise without quietly reducing specifications everywhere. If a proposal exceeds your budget, discuss which items can be simplified or completed later.</p></div>
    <h3 className="mb-5 mt-9 font-serif text-2xl">Why two 2BHK homes can have very different interior budgets</h3><div className="grid gap-5 md:grid-cols-2"><div className="journal-card"><p className="journal-eyebrow">Home A · focused scope</p><h3 className="my-4 text-xl font-semibold">The everyday essentials</h3><p className="leading-7">A modular kitchen, essential wardrobes and a simple TV unit, with existing flooring and electrical points retained. The aim is to make a few important spaces work well.</p></div><div className="journal-card !bg-[#eeece8]"><p className="journal-eyebrow">Home B · expanded scope</p><h3 className="my-4 text-xl font-semibold">More rooms, more details</h3><p className="leading-7">Additional wardrobes, premium hardware, false ceilings, revised lighting and customised furniture. Each addition changes quantities, coordination and the installation work required.</p></div></div>
    <div className="journal-prose mt-7"><p>These are scope examples, not priced packages. Before comparing totals, ask both teams to quote the same room list, dimensions and finish level. Include applicable taxes, transport, installation and any building-related charges that fall to you. Keep an allowance for decisions that cannot be settled until the site has been inspected.</p></div><Link href="/price-calculator" className="journal-button mt-6">Calculate My Interior Cost</Link>
  </Section>;
}

export function MaterialsGuide() {
  const materials = [
    ["Boards and shutters", "Identify the carcass board and shutter material separately, including brand, grade and thickness. Ask why each has been proposed for that location and how exposed edges will be finished."],
    ["Finishes and edge banding", "Record the laminate or finish specification, colour and texture. Check a physical sample where possible; lighting and screens can change how a finish appears. Ask how visible edges and joints are treated."],
    ["Hardware and drawer systems", "Request the hardware brand and exact series for hinges, channels and drawer systems. Try the opening action and ask about load suitability, access and replacement availability."],
    ["Countertops and accessories", "Confirm countertop material, thickness, cut-outs and installation scope. List baskets, organisers and other accessories individually so a design image does not become an assumption about what is included."],
    ["Paint and electrical work", "Separate surface preparation from painting and distinguish fixtures from wiring or point changes. Ask who coordinates these works and checks their completion before cabinets are fitted."],
  ];
  return <Section id="materials" title="Don’t Compare Only the Final Price" eyebrow="Look inside the quotation"><p className="journal-intro">Two quotations can show the same total and still offer very different interiors.</p><div className="grid gap-4 md:grid-cols-2">{materials.map(([title, text]) => <div key={title} className="journal-card"><h3 className="mb-3 font-semibold">{title}</h3><p className="text-sm leading-7">{text}</p></div>)}<aside className="journal-card !bg-primary !text-white"><h3 className="mb-4 text-xl">Before paying, ask</h3><ul className="list-disc space-y-2 pl-5 text-sm leading-6">{["What board are you using?", "What hardware brand and series?", "What exactly is included and excluded?", "Can materials change later?", "Is installation included?", "What does the warranty actually cover?"].map(q => <li key={q}>{q}</li>)}</ul></aside></div><div className="journal-prose mt-8"><p>A material list is useful only if it is connected to the drawings. Ask the team to identify where each specification applies: the kitchen carcass, wardrobe interior and visible shutters may not use the same product. Keep the approved list with your quotation and request written approval for substitutions.</p><p>Warranty discussions should be equally specific. Ask whether coverage comes from the interior company or the product manufacturer, what documentation you receive and what maintenance is expected. Do not assume that a long headline warranty covers every material or every kind of repair.</p></div></Section>;
}

export function ProjectTimeline() {
  const steps = [
    ["Design and revisions", "Allow time for measurements, layout options and decisions. Ask how many revisions are included and who needs to approve them. A clear brief helps prevent repeated changes later."],
    ["Materials and design approval", "Finalise finishes, appliances and hardware together with the drawings. Confirm what becomes fixed when you sign off, and how a later change affects price or production."],
    ["Site readiness and civil work", "Confirm access, electrical and plumbing requirements, any demolition, and building permissions. Ask which tasks must be completed before manufacturing or installation can proceed."],
    ["Production and procurement", "Ask when the order enters production and which items have separate lead times. Keep a record of approved specifications so substitutions are discussed before delivery."],
    ["Installation and coordination", "Agree on material movement, working hours and the sequence of trades. Find out who checks measurements on arrival and how damage or missing items are reported."],
    ["Snag correction and handover", "Walk through the finished work together, record outstanding items and agree on their resolution. Collect care instructions, warranty documents and your after-sales contact."],
  ];
  return <Section id="timeline" title="How Long Will My Interiors Take?" eyebrow="A sequence, not just a number"><p className="journal-intro">Ask for the complete journey from first design to move-in. A manufacturing or installation period may cover only part of that journey.</p><ol className="mt-8 divide-y divide-primary/15 border-y border-primary/15">{steps.map(([title, text], i) => <li key={title} className="grid gap-4 py-7 sm:grid-cols-[48px_1fr_1.5fr]"><span className="text-sm text-secondary">0{i + 1}</span><h3 className="font-serif text-2xl">{title}</h3><p className="text-sm leading-7">{text}</p></li>)}</ol><p className="journal-intro mt-7">Before relying on a promised date, ask what starts the clock, which approvals it assumes and how delays will be communicated. Request a schedule for your own scope rather than applying another homeowner’s timeline to your project.</p></Section>;
}

export function WhoShouldChooseWhat() {
  const scenarios = [
    ["I want an organised service platform", "Use the company summaries to shortlist relevant offerings, then meet the people who will actually handle your project. Compare the scope and escalation process; organisation size alone does not establish fit."],
    ["I want lots of design inspiration", "Explore room galleries, but bring the discussion back to your floor plan. Ask the designer to explain which elements in your reference images are practical within your space and budget."],
    ["I care most about transparent materials", "Request the same specification sheet from every shortlisted company. Compare board grades, hardware series, finishes and substitution rules. The clearest written response is more useful than a general quality claim."],
    ["I want a personal Bangalore-focused experience", "Include EverySpaces in your shortlist and use the first conversation to discuss how you live, your site and the decisions you want help with. Ask how the designer and project lead will stay involved."],
    ["I want a highly customised home", "Bring examples of the unusual details you want. Ask what can be made, what drawings are provided and what happens if a detail cannot be executed as pictured. Confirm the effect on cost and time."],
    ["I have already received quotations", "Pause before choosing the lowest total. Align the room list, quantities, finishes and exclusions first. You can bring an existing quote to EverySpaces for a conversation about comparing the scope."],
  ];
  return <Section id="how-to-choose" title="So, Which Interior Company Should You Choose?"><div className="grid gap-4 md:grid-cols-2">{scenarios.map(([title, text]) => <div key={title} className="journal-card"><h3 className="mb-4 font-serif text-2xl">“{title}”</h3><p className="text-sm leading-7">{text}</p></div>)}</div></Section>;
}

export function BangaloreGuide() {
  return <Section id="bangalore-guide" title="Choosing an Interior Designer in Bangalore Is a Little Different"><div className="journal-prose"><p>Your building’s practical requirements deserve a place in the design conversation. Check apartment association working hours, lift protection, delivery access, material storage and debris removal before agreeing on an installation sequence. Rules differ by building; ask your association for its current requirements.</p><p>If you are planning around a move-in date, tell the designer which rooms must be usable first. Ask how dust, noise and unfinished work will be managed if you expect to occupy the home during installation. A clear site-access plan helps everyone understand what is possible.</p><p>For a compact apartment, test wardrobe door swings, kitchen circulation and storage access on the actual plan. If you work from home, discuss daylight, charging points and a quiet place for calls. In a villa, ask about coordination across floors, material movement and the sequencing of larger spaces.</p><p>Look at ventilation and natural light before selecting finishes or adding tall storage. Ask where samples can be seen locally and who is available to resolve site questions. These are practical checks to raise with any company, not assumptions about how every Bangalore home works.</p><p>Explore our <Link href="/bangalore">Bangalore services</Link> and local information for <Link href="/bangalore/whitefield">Whitefield</Link>, <Link href="/bangalore/hsr-layout">HSR Layout</Link>, <Link href="/bangalore/sarjapur-road">Sarjapur Road</Link> and <Link href="/bangalore/bellandur">Bellandur</Link>.</p></div></Section>;
}

export function PreBookingChecklist() {
  return <Section id="checklist" title="12 Questions to Ask Any Interior Company Before You Pay" eyebrow="Keep this for your consultations"><p className="journal-intro">Bring the same list to every meeting. Record the answers next to the quotation so you can compare proposals calmly at home.</p><ol className="grid gap-x-10 gap-y-0 md:grid-cols-2">{checklist.map((q, i) => <li key={q} className="flex gap-4 border-b border-primary/15 py-5"><span className="text-secondary">{String(i + 1).padStart(2, "0")}</span><span>{q}</span></li>)}</ol><PrintChecklist /></Section>;
}

export function FinalVerdict() {
  return <Section id="verdict" title="Choose the team you trust with your home" eyebrow="The final word"><div className="journal-prose"><p>There is no single interior company that is perfect for every Bangalore home. Your decision should reflect the design you need, the clarity of the proposal and how confidently you can work with the team.</p><p>Shortlist two or three options and give them the same brief. Compare the drawings and specifications, ask about the difficult parts of your site and check how changes will be handled. A useful consultation leaves you understanding more than when you arrived.</p><p>If you want a personal design conversation, clear project guidance and a home considered around your routines, EverySpaces is worth including. You do not have to decide today. Start with a conversation, compare the scope and choose when the details make sense to you.</p></div><div className="mt-6"><ConsultationLink>Discuss My Home With EverySpaces</ConsultationLink></div></Section>;
}

export function ComparisonFAQ() {
  return <Section id="faq" title="Frequently Asked Questions"><div className="mx-auto max-w-3xl divide-y divide-primary/15 border-y border-primary/15">{faqs.map(([q, a]) => <details key={q} className="group py-5"><summary className="cursor-pointer py-2 pr-5 text-lg font-medium">{q}</summary><p className="pb-3 pt-4 text-base leading-8 text-muted-foreground">{a}</p></details>)}</div></Section>;
}
