import Link from "next/link";
import { Section, ConsultationLink } from "./ComparisonSections";

export function ShortlistMethodology() {
  const criteria = [
    ["Bangalore relevance", "An official website identifies Bangalore service, local projects or an experience centre. Check coverage for your exact address directly."],
    ["Residential focus", "The published offering includes home interiors or residential design. This guide is for homeowners, not a ranking of commercial architects."],
    ["Information to explore", "There is an official service description, process or portfolio you can inspect before arranging a consultation."],
    ["Different starting points", "The shortlist includes modular, full-home, renovation and design-focused offerings, so you can explore options against your own brief."],
  ];
  return <Section id="methodology" title="How we selected these ten companies" eyebrow="Read this before the list"><p className="journal-intro">This is an editorial starting point, not an exhaustive survey of Bangalore. We selected companies whose official sites offer enough relevant information to begin a residential design comparison. Smaller studios outside this list may also be a good fit.</p><div className="grid gap-4 md:grid-cols-2">{criteria.map(([title, text]) => <div className="journal-card" key={title}><h3 className="mb-3 font-semibold">{title}</h3><p className="text-sm leading-7">{text}</p></div>)}</div><div className="journal-prose mt-7"><p>We checked public information on 9 September 2026. We did not independently inspect workmanship, verify customer satisfaction, compare standardised quotations or test after-sales support. Company websites describe their own offerings; a statement there is not a guarantee for your project.</p><p>The profiles distinguish published descriptions from our suggestions about potential fit. We do not use star ratings, project counts, discount claims or headline delivery promises to decide an order. The list is alphabetical, and EverySpaces is assessed using the same questions.</p></div></Section>;
}

export function ShortlistDecisionGuide() {
  return <>
    <Section id="choose" title="Find the right fit before you compare prices" eyebrow="Your home, your priorities"><div className="journal-prose"><p>The most useful shortlist starts with your requirements. Write down what must work better in your home: everyday kitchen storage, wardrobes for a growing family, a quiet place to work or a consistent design across all rooms. Separate these needs from the decorative details you would like to add.</p><p>Choose two or three companies whose published work feels relevant. Give every team the same floor plan, room list and budget range. This lets you compare their responses to one problem, rather than comparing unrelated packages.</p></div><div className="mt-8 grid gap-4 md:grid-cols-3">{[
      ["For a compact apartment", "Ask the designer to show door swings, passage widths, storage access and appliance clearances on a measured plan. More cabinetry is not automatically better if it makes everyday movement difficult."],
      ["For a complete home", "Look for coordination between rooms, finishes and trades. Ask for a single scope that explains which team handles cabinetry, lighting, ceilings and any civil work, including what you must arrange separately."],
      ["For a customised villa", "Discuss unusual dimensions, multi-floor coordination, furniture and detailed drawings early. Ask for relevant examples and confirm whether specialist work needs separate consultants or contractors."],
    ].map(([title, text]) => <div key={title} className="journal-card"><h3 className="mb-4 font-serif text-2xl">{title}</h3><p className="text-sm leading-7">{text}</p></div>)}</div><p className="journal-intro mt-7">For a closer look at four frequently compared brands and EverySpaces, read our <Link className="underline underline-offset-4" href="/articles/homelane-vs-designcafe-vs-truww-vs-livspace">HomeLane vs DesignCafe vs Truww vs Livspace comparison</Link>.</p></Section>
    <Section id="budget" title="What affects interior design costs in Bangalore?" eyebrow="Compare the same scope"><p className="journal-intro">A 2BHK label does not describe how much furniture you need, how much site work is involved or which finishes you choose. Start with quantities and specifications.</p><div className="grid gap-4 md:grid-cols-2">{[
      ["The amount of work", "Count the kitchen units, wardrobes, storage pieces and rooms included. Keep movable furniture, curtains, appliances and decorative lighting visible as separate decisions."],
      ["Materials and finishes", "Identify the board brand, grade and thickness; then specify shutters, laminates or other finishes. Ask to see samples and clarify whether substitutions require approval."],
      ["Hardware and accessories", "Compare exact hinge, channel and drawer-system series. A quote with basic shelves is different from one with pull-outs, organisers and specialised mechanisms."],
      ["Site and supporting work", "Check demolition, electrical changes, plumbing, painting, ceilings, transport and installation. Include applicable taxes and ask whether building-related charges are your responsibility."],
    ].map(([title, text]) => <div key={title} className="journal-card"><h3 className="mb-3 font-semibold">{title}</h3><p className="text-sm leading-7">{text}</p></div>)}</div><div className="journal-prose mt-8"><p>Consider two apartments with the same floor plan. One needs a kitchen and two wardrobes, with existing lighting retained. The other needs additional storage, revised electrical points, ceilings and custom furniture. Their totals should differ because the work differs; that alone does not make one quotation expensive.</p><p>Ask for an essentials version and an optional-upgrades version of the proposal. If you need to reduce spending, agree on specific changes instead of accepting vague reductions in material quality. Keep an allowance for unresolved site conditions and decisions still awaiting measurements.</p><p>Our <Link className="underline" href="/services/2bhk-interiors">2BHK</Link>, <Link className="underline" href="/services/3bhk-interiors">3BHK</Link> and <Link className="underline" href="/services/full-home-design">full-home design</Link> pages can help you define the rooms and services you want to discuss.</p></div><Link href="/price-calculator" className="journal-button mt-6">Estimate My Interior Cost</Link></Section>
    <Section id="brand-or-studio" title="Large interior brand or local studio?" eyebrow="Meet the actual team"><div className="journal-prose"><p>A larger organisation may offer several service categories and display options. A smaller studio may offer a more direct design relationship. These are possibilities to investigate, not reliable shortcuts for predicting quality. Either arrangement needs clear responsibilities and a written scope.</p><p>Ask who will design your home, whether that person remains involved during execution and who can approve changes. Find out how often you receive updates and how problems move from the site team to someone authorised to resolve them.</p><p>For EverySpaces, the starting point is a personal design conversation followed by clear drawings, finishes, cost and timeline decisions. Explore our <Link className="underline" href="/portfolio">project portfolio</Link> and ask how that process would work for your own home. A good fit should become clear through the discussion and proposal, not just the company’s size.</p></div></Section>
    <Section id="local-planning" title="Plan for your Bangalore site, not just the showroom"><div className="journal-prose"><p>Before setting a move-in target, check the building’s work timings, lift access, delivery arrangements and requirements for protecting common areas. These rules vary by property. Ask your association or property manager for the current requirements and share them with the interior team.</p><p>Confirm where materials can be stored, who removes debris and how workers access the apartment. If you will live in the home during work, discuss dust control, usable rooms and the daily handover of the site. For a new apartment, distinguish builder possession from readiness for interior installation.</p><p>Ask for design approval, procurement, production, civil work, installation and snag correction to appear separately in the schedule. Clarify what starts any promised delivery period and what happens if appliances, measurements or approvals change.</p><p>For local EverySpaces information, explore <Link className="underline" href="/bangalore/whitefield">Whitefield</Link>, <Link className="underline" href="/bangalore/hsr-layout">HSR Layout</Link>, <Link className="underline" href="/bangalore/sarjapur-road">Sarjapur Road</Link> and our <Link className="underline" href="/bangalore">Bangalore service areas</Link>. Confirm service availability at your address during consultation.</p></div></Section>
    <Section id="second-opinion" title="Already have a quotation?" eyebrow="Make the next conversation useful"><p className="journal-intro">Bring your floor plan and quote. We’ll help you discuss the scope, materials and design choices so you can understand what you’re comparing before making a decision.</p><ConsultationLink>Get a Second Opinion</ConsultationLink></Section>
  </>;
}
