// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjljizsnwwukbzdfpmuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqbGppenNud3d1a2J6ZGZwbXV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2MDg3OTIsImV4cCI6MjA4OTE4NDc5Mn0.yRIO5z4zxzJkL9TlCHu_SEEELjlp_zNAfRZeqkgCfq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});